version: "3.9"

services:
  currency-conversion-db:
    image: postgres:14-alpine
    container_name: Currency-Conversion-DB
    hostname: currency-conversion-db
    ports:
      - "15432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - ./database/currency-conversion-db:/var/lib/postgresql/data:rw
      - ./database/schema:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      restart: on-failure:5