CREATE SCHEMA IF NOT EXISTS CURRENCY_CONVERSION;
ALTER SCHEMA CURRENCY_CONVERSION OWNER TO postgres;
GRANT CONNECT ON DATABASE jaya_tech to postgres;
GRANT USAGE ON SCHEMA CURRENCY_CONVERSION TO postgres;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA CURRENCY_CONVERSION TO postgres;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA CURRENCY_CONVERSION TO postgres;