name: CD Pipeline

on:
  push:
    branches: [ develop ]

jobs:

  build-and-push:
    runs-on: ubuntu-latest
    environment:
      name: 'Docker Hub'

    steps:

      - name: Code checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PWD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USER }}/currency-converter:latest
            ${{ secrets.DOCKERHUB_USER }}/currency-converter:${{ github.sha }}
